baseURL = 'http://mat-k.dev/'
languageCode = 'en-us'
title = 'Mat is not a webdev'

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"

    url = "/pages/projects"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Projects"

    # Weights are used to determine the ordering
    weight = 1

[params]
  # URL for the avatar on homepage
  avatarURL = "img/surf.jpg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xl"

  # Description to display on homepage
  description = "Matthew Knight - Computer Systems Engineer"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)

  # Footer text
  footer = "gg ez"

  socialIcons = [
      {name = "github", url = "https://github.com/Mat124"},
      {name = "linkedin", url = "https://www.linkedin.com/in/matthew-knight-505b27192/"},
      {name = "email", url = "mailto:mrg.knight1@gmail.com"},
    ]